apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      #- image: dockersamples/examplevotingapp_result
      - image: luizcarloskazuyukifukaya/result:dev
        name: result
        ports:
        - containerPort: 80
          name: result
