apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      #- image: dockersamples/examplevotingapp_vote
      - image: luizcarloskazuyukifukaya/vote:dev
        name: vote
        ports:
        - containerPort: 80
          name: vote
