apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      #- image: dockersamples/examplevotingapp_worker
      - image: luizcarloskazuyukifukaya/worker:dev
        imagePullPolicy: Always # IMPORTANT to always pull updated image
        name: worker
